openapi: 3.1.0
info:
  title: Travel Agency API
  version: 1.0.0
  description: REST API documentation for the Travel Agency backend
servers:
  - url: /api/v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
